/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipos.vista;




import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.Calendar;
import javax.swing.JOptionPane;
import prototipos.controlador.clsEmpleado;
import prototipos.controlador.clsPuesto;
import prototipos.modelo.daoEmpleado;
import prototipos.modelo.daoPuesto;

/**
 *
 * @author visitante
 */
public class frmProcesoEmpleado extends javax.swing.JInternalFrame {

    
    public void llenadoCombo(){
                daoPuesto conceptoDAO = new daoPuesto();
        List<clsPuesto> concepto = conceptoDAO.select();
        
        cbxPuesto.addItem("Seleccione Un Codigo");
        for (int i = 0; i < concepto.size(); i++) {
            cbxPuesto.addItem(String.valueOf(concepto.get(i).getId()));
        }
        
    }
  

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID ");
        modelo.addColumn("P.NOMBRE");
        modelo.addColumn("S.NOMBRE");
        modelo.addColumn("P.APELLIDO");
        modelo.addColumn("S.APELLIDO");
        modelo.addColumn("CORREO");
        modelo.addColumn("PUESTO");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("FECHA");
        modelo.addColumn("NIT");
        modelo.addColumn("DPI");
        daoEmpleado productoDAO = new daoEmpleado();
        List<clsEmpleado> producto = productoDAO.select();
        tablaVendedores.setModel(modelo);
        String[] dato = new String[11];
        for (int i = 0; i < producto.size(); i++) {
            dato[0] = Integer.toString(producto.get(i).getId());
            dato[1] = producto.get(i).getNombre1();
            dato[2] = producto.get(i).getNombre2();
            dato[3] = producto.get(i).getApellido1();
            dato[4] = producto.get(i).getApellido2();
            dato[5] = producto.get(i).getCorreo();
            dato[6] = Integer.toString(producto.get(i).getPuesto());
            dato[7] = producto.get(i).getDireccion();
            dato[8] = producto.get(i).getFecha();
            dato[9] = producto.get(i).getNit();
            dato[10] = producto.get(i).getDpi();
            
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscarProducto() {

        
    }

    public frmProcesoEmpleado() {
        initComponents();
        llenadoDeTablas();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        txtEntrenador = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        txtApellido2 = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        jdFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        label10 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        txtDpi = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        cbxPuesto = new javax.swing.JComboBox<>();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(" Empleado");
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 95, 30));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 95, 30));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label1.setText("EMPLEADO");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 0, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 95, 30));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Empleado");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, 20));
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 102, 20));

        txtEntrenador.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtEntrenador.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, 20));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 95, 30));

        tablaVendedores.setBackground(new java.awt.Color(204, 255, 255));
        tablaVendedores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        tablaVendedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedor", "ID Empleado", "Correo", "Telefono", "Direccion", "Porcentaje", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVendedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 612, 440));

        txtApellido2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtApellido2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 220, 20));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("DPI");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 100, 30));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label6.setText("PRIMER NOMBRE");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 100, -1, -1));

        label7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label7.setText("SEGUNDO NOMBRE");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 220, 20));

        txtNombre2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombre2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 220, 20));

        label4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label4.setText("ID EMPLEADO");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, -1, -1));

        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 40, 20));

        txtApellido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 220, 20));

        label8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label8.setText("PRIMER APELLIDO");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label9.setText("Fecha Nacimiento");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));
        getContentPane().add(jdFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 120, -1));

        jLabel1.setText("INGRESE SUS DATOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 80, -1));

        label10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label10.setText("SEGUNDO APELLIDO");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        label11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label11.setText("CORREO");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        label12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label12.setText("ID PUESTO");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        label13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label13.setText("DIRECCION");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        label14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label14.setText("NIT");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));
        getContentPane().add(txtDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 220, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 220, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 220, -1));
        getContentPane().add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 220, -1));

        cbxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(cbxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        daoEmpleado productoDAO = new daoEmpleado();
        clsEmpleado  productoAEliminar = new clsEmpleado ();
        productoAEliminar.setId(Integer.parseInt(txtbuscado.getText()));
        productoDAO.delete(productoAEliminar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        daoEmpleado productoDAO = new daoEmpleado();
        clsEmpleado productoAInsertar = new clsEmpleado();
        productoAInsertar.setId(Integer.parseInt(txtEntrenador.getText()));
        productoAInsertar.setNombre1(txtNombre.getText());
        productoAInsertar.setNombre2(txtNombre2.getText());
        productoAInsertar.setApellido2(txtApellido2.getText());
        productoAInsertar.setApellido1(txtApellido.getText());
        productoAInsertar.setCorreo(txtCorreo.getText());
        productoAInsertar.setPuesto(Integer.parseInt(String.valueOf(cbxPuesto.getSelectedItem())));
        productoAInsertar.setDireccion(txtDireccion.getText());
        String dia = Integer.toString(jdFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jdFecha.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(jdFecha.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes + "-" + dia);
        System.out.println(fecha);
        productoAInsertar.setFecha(fecha);
        productoAInsertar.setNit(txtNit.getText());
        productoAInsertar.setDpi(txtDpi.getText());       
        productoDAO.insert(productoAInsertar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
//        // TODO add your handling code here:
        daoEmpleado productoDAO = new daoEmpleado();
        clsEmpleado productoAActualizar = new clsEmpleado();
        productoAActualizar.setId(Integer.parseInt(txtbuscado.getText()));
        productoAActualizar.setNombre1(txtNombre.getText());
        productoAActualizar.setNombre2(txtNombre2.getText());
        productoAActualizar.setApellido2(txtApellido2.getText());
        productoAActualizar.setApellido1(txtApellido.getText());
         String dia = Integer.toString(jdFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jdFecha.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(jdFecha.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes + "-" + dia);
        System.out.println(fecha);
      
        
        productoAActualizar.setFecha(fecha);
        productoDAO.update(productoAActualizar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       
        txtEntrenador.setText("");
        txtApellido2.setText("");
        txtbuscado.setText("");
        txtNombre.setText("");
        txtNombre2.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtNit.setText("");
        txtDpi.setText("");
        txtFecha.setText("");
        
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "INGRESE EL CODIGO DEL PRODUCTO QUE DESEA BUSCAR,ELIMINAR O REGISTRAR");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxPuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDpi;
    private javax.swing.JTextField txtEntrenador;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
